### ISSUE TITLE
tworzenie wizyty (Home/ Wizyty/ Nowa wizyta)

### ISSUE THREAD

**Issue by SuperJaba** [HubertPel/szczepionka#31]
selectbox userow nie ma zadnych wartosc
![image](https://github.com/HubertPel/szczepionka/assets/22955646/1f862e37-dafd-41e4-9f60-056c0511bc1c)

**Comment by HubertPel** [comment]
tu generalnie powinni sie wyświetlać sami użytkownicy bez pracowników i adminów bo tylko użytkownik może zapisać sie na wizytę
